sudo: required
services:
  - docker

before_install:
  - docker build -t shivanshchauhan416/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivanshchauhan416/docker-react npm run test -- --coverage
